default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ticketwin_development

test:
  <<: *default
  database: ticketwin_test

production:
  <<: *default
  database: ticketwin_production
